Resources:

  BucketHowBootcampS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-howbootcamps3
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True